


applications:
- name : quiz
memory : 512M
instances : 1
path: target/quiz.jar

---
spring:
profiles: production
datasource:
 url: jdbc:mysql://https://node9317-hamdi.p4d.click/Quiz
 username: root
password: fZ9L6LdDTa




